#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Web.UserEmails
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\UserEmails\AuthConfirmationResult.cshtml"
    using SP.DataAccess;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class AuthConfirmationResult : SP.Web.UserEmails.CourseParticipantEmailBase
    {
#line hidden
        #line 5 "..\..\UserEmails\AuthConfirmationResult.cshtml"
           
    public Participant Auth { get; set; }
    public bool IsChanged { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 9 "..\..\UserEmails\AuthConfirmationResult.cshtml"
   Layout = new SP.Web.UserEmails.LayoutTemplate { Title = "Confirmation Changed" }; 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<table");

WriteLiteral(" class=\"callout\"");

WriteLiteral(" style=\"Margin-bottom: 16px; border-collapse: collapse; border-spacing: 0; margin" +
"-bottom: 16px; padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" class=\"callout-inner info\"");

WriteLiteral(" style=\"Margin: 0; background: #fefefe; border: 1px solid #cbcbcb; color: #0a0a0a" +
"; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: norma" +
"l; line-height: 1.3; margin: 0; padding: 10px; text-align: left; width: 100%;\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n        <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 15 "..\..\UserEmails\AuthConfirmationResult.cshtml"
           Write(Auth.FullName);

            
            #line default
            #line hidden
WriteLiteral(" has \r\n                <strong>\r\n");

WriteLiteral("                    ");

            
            #line 17 "..\..\UserEmails\AuthConfirmationResult.cshtml"
                Write(IsChanged?"accepted":"declined");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </strong> \r\n                your request to change confirmation" +
" status.\r\n            </p>\r\n            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\UserEmails\AuthConfirmationResult.cshtml"
           Write(CourseParticipant.Participant.FullName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 22 "..\..\UserEmails\AuthConfirmationResult.cshtml"
                                                    Write(IsChanged?"is now":"remains");

            
            #line default
            #line hidden
WriteLiteral(" registered as \r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\UserEmails\AuthConfirmationResult.cshtml"
            Write(CourseParticipant.IsConfirmed.Value?"attending":"not attending");

            
            #line default
            #line hidden
WriteLiteral(".\r\n            </p>\r\n        </th>\r\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n    </tr></tbody></table>\r\n</th><th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table>\r\n\r\n\r\n");

            
            #line 31 "..\..\UserEmails\AuthConfirmationResult.cshtml"
 if(!IsChanged) { 

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n        <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">If you would like to discuss this further, you may wish to contact one of the or" +
"ganiser(s) below:</p>\r\n            <ul>\r\n");

            
            #line 36 "..\..\UserEmails\AuthConfirmationResult.cshtml"
                
            
            #line default
            #line hidden
            
            #line 36 "..\..\UserEmails\AuthConfirmationResult.cshtml"
                 foreach(var o in (from cp in CourseParticipant.Course.CourseParticipants where cp.IsOrganiser select cp.Participant)){

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4786), Tuple.Create("\"", 4810)
, Tuple.Create(Tuple.Create("", 4793), Tuple.Create("mailto:", 4793), true)
            
            #line 38 "..\..\UserEmails\AuthConfirmationResult.cshtml"
, Tuple.Create(Tuple.Create("", 4800), Tuple.Create<System.Object, System.Int32>(o.Email
            
            #line default
            #line hidden
, 4800), false)
);

WriteLiteral(" style=\"Margin: 0; color: #2199e8; font-family: Helvetica, Arial, sans-serif; fon" +
"t-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; tex" +
"t-decoration: none;\"");

WriteLiteral(">");

            
            #line 38 "..\..\UserEmails\AuthConfirmationResult.cshtml"
                                                                                                                                                                                                                                    Write(o.FullName);

            
            #line default
            #line hidden
WriteLiteral("</a> Tel: ");

            
            #line 38 "..\..\UserEmails\AuthConfirmationResult.cshtml"
                                                                                                                                                                                                                                                         Write(o.PhoneNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 40 "..\..\UserEmails\AuthConfirmationResult.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </th>\r\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n    </tr></tbody></table>\r\n");

            
            #line 45 "..\..\UserEmails\AuthConfirmationResult.cshtml"
}
            
            #line default
            #line hidden
WriteLiteral(" ");

        }
    }
}
#pragma warning restore 1591
