#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Web.UserEmails
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\UserEmails\basic.cshtml"
    using SP.DataAccess;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class basic : SP.Web.UserEmails.CourseParticipantEmailBase
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<table");

WriteLiteral(" class=\"wrapper header\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(" class=\"wrapper-inner\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">\r\n  <table");

WriteLiteral(" align=\"center\"");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"Margin: 0 auto; background: #fefefe; border-collapse: collapse; border-sp" +
"acing: 0; margin: 0 auto; padding: 0; text-align: inherit; vertical-align: top; " +
"width: 580px;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"row collapse\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0;" +
" position: relative; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n      <th");

WriteLiteral(" class=\"small-6 large-6 columns first\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0; padding-right: 0; text-align: left; width: 298px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <img");

WriteLiteral(" src=\"http://placehold.it/200x50/663399\"");

WriteLiteral(" style=\"-ms-interpolation-mode: bicubic; clear: both; display: block; max-width: " +
"100%; outline: none; text-decoration: none; width: auto;\"");

WriteLiteral(">\r\n      </th></tr></table></th>\r\n      <th");

WriteLiteral(" class=\"small-6 large-6 columns last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0; padding-right: 0; text-align: left; width: 298px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <p");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: right;\"");

WriteLiteral(">BASIC</p>\r\n      </th></tr></table></th>\r\n    </tr></tbody></table>\r\n  </td></tr" +
"></tbody></table>\r\n</td></tr></table>\r\n\r\n<table");

WriteLiteral(" align=\"center\"");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"Margin: 0 auto; background: #fefefe; border-collapse: collapse; border-sp" +
"acing: 0; margin: 0 auto; padding: 0; text-align: inherit; vertical-align: top; " +
"width: 580px;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">\r\n\r\n  <table");

WriteLiteral(" class=\"spacer\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(" height=\"16px\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">&#xA0;</td></tr></tbody></table> \r\n  \r\n  <table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0;" +
" position: relative; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n    <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n      \r\n      <h1");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 34px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left; word-wrap: normal;\"");

WriteLiteral(">Hi, Susan Calvin</h1>\r\n      <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 20px; font-weight: normal; line-height: 1.6; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni, iste, amet cons" +
"equatur a veniam.</p>\r\n      <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(@">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut optio nulla et, fugiat. Maiores accusantium nostrum asperiores provident, quam modi ex inventore dolores id aspernatur architecto odio minima perferendis, explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima quos quasi itaque beatae natus fugit provident delectus, magnam laudantium odio corrupti sit quam. Optio aut ut repudiandae velit distinctio asperiores?</p>
      <table");

WriteLiteral(" class=\"callout\"");

WriteLiteral(" style=\"Margin-bottom: 16px; border-collapse: collapse; border-spacing: 0; margin" +
"-bottom: 16px; padding: 0; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" class=\"callout-inner primary\"");

WriteLiteral(" style=\"Margin: 0; background: #def0fc; border: 1px solid #444444; color: #0a0a0a" +
"; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: norma" +
"l; line-height: 1.3; margin: 0; padding: 10px; text-align: left; width: 100%;\"");

WriteLiteral(">\r\n        <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit repellen" +
"dus natus, sint ea optio dignissimos asperiores inventore a molestiae dolorum pl" +
"aceat repellat excepturi mollitia ducimus unde doloremque ad, alias eos!</p>\r\n  " +
"    </th><th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table>\r\n    </th>\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n  </tr></tbody></table>\r\n  <table");

WriteLiteral(" class=\"wrapper secondary\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(" class=\"wrapper-inner\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">\r\n\r\n    <table");

WriteLiteral(" class=\"spacer\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(" height=\"16px\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">&#xA0;</td></tr></tbody></table> \r\n\r\n    <table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0;" +
" position: relative; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n      <th");

WriteLiteral(" class=\"small-12 large-6 columns first\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 8px; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <h5");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 20px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left; word-wrap: normal;\"");

WriteLiteral(">Connect With Us:</h5>\r\n        <table");

WriteLiteral(" class=\"button facebook expand\"");

WriteLiteral(" style=\"Margin: 0 0 16px 0; border-collapse: collapse; border-spacing: 0; margin:" +
" 0 0 16px 0; padding: 0; text-align: left; vertical-align: top; width: 100% !imp" +
"ortant;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #2199e8; border: 2px solid #2199e8; border-collapse: collapse !important; color: #fefefe; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><center");

WriteLiteral(" data-parsed=\"\"");

WriteLiteral(" style=\"min-width: 0; width: 100%;\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://zurb.com\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" class=\"float-center\"");

WriteLiteral(@" style=""Margin: 0; border: 0 solid #2199e8; border-radius: 3px; color: #fefefe; display: inline-block; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: bold; line-height: 1.3; margin: 0; padding: 8px 16px 8px 16px; padding-left: 0; padding-right: 0; text-align: center; text-decoration: none; width: 100%;""");

WriteLiteral(">Facebook</a></center></td></tr></table></td>\n<td");

WriteLiteral(" class=\"expander\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0 !important; text-align: left; vertical-align: top; visibility: hidden; width: 0; word-wrap: break-word;""");

WriteLiteral("></td></tr></table>\r\n        <table");

WriteLiteral(" class=\"button twitter expand\"");

WriteLiteral(" style=\"Margin: 0 0 16px 0; border-collapse: collapse; border-spacing: 0; margin:" +
" 0 0 16px 0; padding: 0; text-align: left; vertical-align: top; width: 100% !imp" +
"ortant;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #2199e8; border: 2px solid #2199e8; border-collapse: collapse !important; color: #fefefe; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><center");

WriteLiteral(" data-parsed=\"\"");

WriteLiteral(" style=\"min-width: 0; width: 100%;\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://zurb.com\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" class=\"float-center\"");

WriteLiteral(@" style=""Margin: 0; border: 0 solid #2199e8; border-radius: 3px; color: #fefefe; display: inline-block; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: bold; line-height: 1.3; margin: 0; padding: 8px 16px 8px 16px; padding-left: 0; padding-right: 0; text-align: center; text-decoration: none; width: 100%;""");

WriteLiteral(">Twitter</a></center></td></tr></table></td>\n<td");

WriteLiteral(" class=\"expander\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0 !important; text-align: left; vertical-align: top; visibility: hidden; width: 0; word-wrap: break-word;""");

WriteLiteral("></td></tr></table>\r\n        <table");

WriteLiteral(" class=\"button google expand\"");

WriteLiteral(" style=\"Margin: 0 0 16px 0; border-collapse: collapse; border-spacing: 0; margin:" +
" 0 0 16px 0; padding: 0; text-align: left; vertical-align: top; width: 100% !imp" +
"ortant;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #2199e8; border: 2px solid #2199e8; border-collapse: collapse !important; color: #fefefe; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><center");

WriteLiteral(" data-parsed=\"\"");

WriteLiteral(" style=\"min-width: 0; width: 100%;\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://zurb.com\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" class=\"float-center\"");

WriteLiteral(@" style=""Margin: 0; border: 0 solid #2199e8; border-radius: 3px; color: #fefefe; display: inline-block; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: bold; line-height: 1.3; margin: 0; padding: 8px 16px 8px 16px; padding-left: 0; padding-right: 0; text-align: center; text-decoration: none; width: 100%;""");

WriteLiteral(">Google+</a></center></td></tr></table></td>\n<td");

WriteLiteral(" class=\"expander\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0 !important; text-align: left; vertical-align: top; visibility: hidden; width: 0; word-wrap: break-word;""");

WriteLiteral("></td></tr></table>\r\n      </th></tr></table></th>\r\n      <th");

WriteLiteral(" class=\"small-12 large-6 columns last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 8px; padding-right: 16px; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <h5");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 20px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left; word-wrap: normal;\"");

WriteLiteral(">Contact Info:</h5>\r\n        <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">Phone: 408-341-0600</p>\r\n        <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">Email: <a");

WriteLiteral(" href=\"mailto:foundation@zurb.com\"");

WriteLiteral(" style=\"Margin: 0; color: #2199e8; font-family: Helvetica, Arial, sans-serif; fon" +
"t-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; tex" +
"t-decoration: none;\"");

WriteLiteral(">foundation@zurb.com</a></p>\r\n      </th></tr></table></th>\r\n    </tr></tbody></t" +
"able>\r\n  </td></tr></table>\r\n</td></tr></tbody></table>\r\n");

        }
    }
}
#pragma warning restore 1591
