#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Web.UserEmails
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class LayoutTemplate : SP.Web.UserEmails.EmailBase
    {
#line hidden
        #line 4 "..\..\UserEmails\LayoutTemplate.cshtml"
            
    public string Title{ get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\r\n          \"http:/" +
"/www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" xml:lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(">\r\n    <title>");

            
            #line 14 "..\..\UserEmails\LayoutTemplate.cshtml"
      Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    \r\n    <style>");

WriteLiteral("@media only screen {\n  html {\n    min-height: 100%;\n    background: #f3f3f3;\n  }\n" +
"}\n\n");

WriteLiteral(@"@media only screen and (max-width: 596px) {
  .small-float-center {
    margin: 0 auto !important;
    float: none !important;
    text-align: center !important;
  }

  .small-text-center {
    text-align: center !important;
  }

  .small-text-left {
    text-align: left !important;
  }

  .small-text-right {
    text-align: right !important;
  }
}

");

WriteLiteral(@"@media only screen and (max-width: 596px) {
  .hide-for-large {
    display: block !important;
    width: auto !important;
    overflow: visible !important;
    max-height: none !important;
    font-size: inherit !important;
    line-height: inherit !important;
  }
}

");

WriteLiteral("@media only screen and (max-width: 596px) {\n  table.body table.container .hide-fo" +
"r-large,\n  table.body table.container .row.hide-for-large {\n    display: table !" +
"important;\n    width: 100% !important;\n  }\n}\n\n");

WriteLiteral("@media only screen and (max-width: 596px) {\n  table.body table.container .callout" +
"-inner.hide-for-large {\n    display: table-cell !important;\n    width: 100% !imp" +
"ortant;\n  }\n}\n\n");

WriteLiteral("@media only screen and (max-width: 596px) {\n  table.body table.container .show-fo" +
"r-large {\n    display: none !important;\n    width: 0;\n    mso-hide: all;\n    ove" +
"rflow: hidden;\n  }\n}\n\n");

WriteLiteral("@media only screen and (max-width: 596px) {\n  table.body img {\n    width: auto;\n " +
"   height: auto;\n  }\n\n  table.body center {\n    min-width: 0 !important;\n  }\n\n  " +
"table.body .container {\n    width: 95% !important;\n  }\n\n  table.body .columns,\n " +
" table.body .column {\n    height: auto !important;\n    -moz-box-sizing: border-b" +
"ox;\n    -webkit-box-sizing: border-box;\n    box-sizing: border-box;\n    padding-" +
"left: 16px !important;\n    padding-right: 16px !important;\n  }\n\n  table.body .co" +
"lumns .column,\n  table.body .columns .columns,\n  table.body .column .column,\n  t" +
"able.body .column .columns {\n    padding-left: 0 !important;\n    padding-right: " +
"0 !important;\n  }\n\n  table.body .collapse .columns,\n  table.body .collapse .colu" +
"mn {\n    padding-left: 0 !important;\n    padding-right: 0 !important;\n  }\n\n  td." +
"small-1,\n  th.small-1 {\n    display: inline-block !important;\n    width: 8.33333" +
"% !important;\n  }\n\n  td.small-2,\n  th.small-2 {\n    display: inline-block !impor" +
"tant;\n    width: 16.66667% !important;\n  }\n\n  td.small-3,\n  th.small-3 {\n    dis" +
"play: inline-block !important;\n    width: 25% !important;\n  }\n\n  td.small-4,\n  t" +
"h.small-4 {\n    display: inline-block !important;\n    width: 33.33333% !importan" +
"t;\n  }\n\n  td.small-5,\n  th.small-5 {\n    display: inline-block !important;\n    w" +
"idth: 41.66667% !important;\n  }\n\n  td.small-6,\n  th.small-6 {\n    display: inlin" +
"e-block !important;\n    width: 50% !important;\n  }\n\n  td.small-7,\n  th.small-7 {" +
"\n    display: inline-block !important;\n    width: 58.33333% !important;\n  }\n\n  t" +
"d.small-8,\n  th.small-8 {\n    display: inline-block !important;\n    width: 66.66" +
"667% !important;\n  }\n\n  td.small-9,\n  th.small-9 {\n    display: inline-block !im" +
"portant;\n    width: 75% !important;\n  }\n\n  td.small-10,\n  th.small-10 {\n    disp" +
"lay: inline-block !important;\n    width: 83.33333% !important;\n  }\n\n  td.small-1" +
"1,\n  th.small-11 {\n    display: inline-block !important;\n    width: 91.66667% !i" +
"mportant;\n  }\n\n  td.small-12,\n  th.small-12 {\n    display: inline-block !importa" +
"nt;\n    width: 100% !important;\n  }\n\n  .columns td.small-12,\n  .column td.small-" +
"12,\n  .columns th.small-12,\n  .column th.small-12 {\n    display: block !importan" +
"t;\n    width: 100% !important;\n  }\n\n  table.body td.small-offset-1,\n  table.body" +
" th.small-offset-1 {\n    margin-left: 8.33333% !important;\n    Margin-left: 8.33" +
"333% !important;\n  }\n\n  table.body td.small-offset-2,\n  table.body th.small-offs" +
"et-2 {\n    margin-left: 16.66667% !important;\n    Margin-left: 16.66667% !import" +
"ant;\n  }\n\n  table.body td.small-offset-3,\n  table.body th.small-offset-3 {\n    m" +
"argin-left: 25% !important;\n    Margin-left: 25% !important;\n  }\n\n  table.body t" +
"d.small-offset-4,\n  table.body th.small-offset-4 {\n    margin-left: 33.33333% !i" +
"mportant;\n    Margin-left: 33.33333% !important;\n  }\n\n  table.body td.small-offs" +
"et-5,\n  table.body th.small-offset-5 {\n    margin-left: 41.66667% !important;\n  " +
"  Margin-left: 41.66667% !important;\n  }\n\n  table.body td.small-offset-6,\n  tabl" +
"e.body th.small-offset-6 {\n    margin-left: 50% !important;\n    Margin-left: 50%" +
" !important;\n  }\n\n  table.body td.small-offset-7,\n  table.body th.small-offset-7" +
" {\n    margin-left: 58.33333% !important;\n    Margin-left: 58.33333% !important;" +
"\n  }\n\n  table.body td.small-offset-8,\n  table.body th.small-offset-8 {\n    margi" +
"n-left: 66.66667% !important;\n    Margin-left: 66.66667% !important;\n  }\n\n  tabl" +
"e.body td.small-offset-9,\n  table.body th.small-offset-9 {\n    margin-left: 75% " +
"!important;\n    Margin-left: 75% !important;\n  }\n\n  table.body td.small-offset-1" +
"0,\n  table.body th.small-offset-10 {\n    margin-left: 83.33333% !important;\n    " +
"Margin-left: 83.33333% !important;\n  }\n\n  table.body td.small-offset-11,\n  table" +
".body th.small-offset-11 {\n    margin-left: 91.66667% !important;\n    Margin-lef" +
"t: 91.66667% !important;\n  }\n\n  table.body table.columns td.expander,\n  table.bo" +
"dy table.columns th.expander {\n    display: none !important;\n  }\n\n  table.body ." +
"right-text-pad,\n  table.body .text-pad-right {\n    padding-left: 10px !important" +
";\n  }\n\n  table.body .left-text-pad,\n  table.body .text-pad-left {\n    padding-ri" +
"ght: 10px !important;\n  }\n\n  table.menu {\n    width: 100% !important;\n  }\n\n  tab" +
"le.menu td,\n  table.menu th {\n    width: auto !important;\n    display: inline-bl" +
"ock !important;\n  }\n\n  table.menu.vertical td,\n  table.menu.vertical th,\n  table" +
".menu.small-vertical td,\n  table.menu.small-vertical th {\n    display: block !im" +
"portant;\n  }\n\n  table.menu[align=\"center\"] {\n    width: auto !important;\n  }\n\n  " +
"table.button.small-expand,\n  table.button.small-expanded {\n    width: 100% !impo" +
"rtant;\n  }\n\n  table.button.small-expand table,\n  table.button.small-expanded tab" +
"le {\n    width: 100%;\n  }\n\n  table.button.small-expand table a,\n  table.button.s" +
"mall-expanded table a {\n    text-align: center !important;\n    width: 100% !impo" +
"rtant;\n    padding-left: 0 !important;\n    padding-right: 0 !important;\n  }\n\n  t" +
"able.button.small-expand center,\n  table.button.small-expanded center {\n    min-" +
"width: 0;\n  }\n}</style>\r\n</head>\r\n<body");

WriteLiteral(@" style=""-moz-box-sizing: border-box; -ms-text-size-adjust: 100%; -webkit-box-sizing: border-box; -webkit-text-size-adjust: 100%; Margin: 0; box-sizing: border-box; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; min-width: 100%; padding: 0; text-align: left; width: 100% !important;""");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"wrapper header\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" style=\"background-color: #000; border-collapse: collapse; border-spacing: 0; pad" +
"ding: 0; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(" class=\"wrapper-inner\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 20px; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"row collapse\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n                <th");

WriteLiteral(" class=\"small-2 large-2 columns first\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; text-align: left; width: 104.66667px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 8778), Tuple.Create("\"", 8827)
            
            #line 326 "..\..\UserEmails\LayoutTemplate.cshtml"
, Tuple.Create(Tuple.Create("", 8784), Tuple.Create<System.Object, System.Int32>(BaseUrl
            
            #line default
            #line hidden
, 8784), false)
, Tuple.Create(Tuple.Create("", 8794), Tuple.Create("images/sim-planner-icon-50x75.png", 8794), true)
);

WriteLiteral(" alt=\"sim-manager logo\"");

WriteLiteral(" height=\"50\"");

WriteLiteral(" width=\"75\"");

WriteLiteral(" style=\"-ms-interpolation-mode: bicubic; clear: both; display: block; max-width: " +
"100%; outline: none; text-decoration: none; width: auto;\"");

WriteLiteral(">\r\n                </th></tr></table></th>\r\n                <th");

WriteLiteral(" class=\"small-8 large-8 columns\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; text-align: left; width: 386.66667px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #fff; font-family: Helvetica, Aria" +
"l, sans-serif; font-size: 34px; font-weight: normal; line-height: 1.3; margin: 0" +
"; margin-bottom: 10px; padding: 0; text-align: center; word-wrap: normal;\"");

WriteLiteral(">Sim-planner</h1>\r\n                </th></tr></table></th>\r\n                <th");

WriteLiteral(" class=\"small-2 large-2 columns last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 0; padding-left: 0; padding-right: 0; text-align: left; width: 104.66667px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"float-right\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10803), Tuple.Create("\"", 10851)
            
            #line 332 "..\..\UserEmails\LayoutTemplate.cshtml"
, Tuple.Create(Tuple.Create("", 10809), Tuple.Create<System.Object, System.Int32>(BaseUrl
            
            #line default
            #line hidden
, 10809), false)
, Tuple.Create(Tuple.Create("", 10819), Tuple.Create("Content/images/logo-starship.png", 10819), true)
);

WriteLiteral(" alt=\"Starship logo\"");

WriteLiteral(" height=\"50\"");

WriteLiteral(" width=\"93\"");

WriteLiteral(" style=\"-ms-interpolation-mode: bicubic; clear: both; display: block; float: righ" +
"t; max-width: 100%; outline: none; text-align: right; text-decoration: none; wid" +
"th: auto;\"");

WriteLiteral(">\r\n                </th></tr></table></th>\r\n            </tr></tbody></table>\r\n  " +
"  </td></tr></table>\r\n    <table");

WriteLiteral(" align=\"center\"");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"Margin: 0 auto; background: #fefefe; border-collapse: collapse; border-sp" +
"acing: 0; margin: 0 auto; padding: 0; text-align: inherit; vertical-align: top; " +
"width: 580px;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"spacer\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(" height=\"16px\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">&#xA0;</td></tr></tbody></table> \r\n        <table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0;" +
" position: relative; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n            <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                <h2");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 30px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: center; word-wrap: normal;\"");

WriteLiteral(">");

            
            #line 340 "..\..\UserEmails\LayoutTemplate.cshtml"
                                                                                                                                                                                                                                                                                 Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n            </th>\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n        </tr></tbody></table>\r\n        \r\n");

WriteLiteral("        ");

            
            #line 345 "..\..\UserEmails\LayoutTemplate.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </td></tr></tbody></table>\r\n\r\n    <table");

WriteLiteral(" class=\"wrapper footer\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" style=\"background-color: transparent; border-collapse: collapse; border-spacing:" +
" 0; padding: 0; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(" class=\"wrapper-inner\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">\r\n        <table");

WriteLiteral(" align=\"center\"");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"Margin: 0 auto; background: #fefefe; background-color: transparent; borde" +
"r-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; text-align:" +
" inherit; vertical-align: top; width: 580px;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"spacer\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(" height=\"16px\"");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral(">&#xA0;</td></tr></tbody></table> \r\n            <table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0;" +
" position: relative; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n                <th");

WriteLiteral(" class=\"small-12 large-6 columns first\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 8px; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                    <h5");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 20px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left; word-wrap: normal;\"");

WriteLiteral(">Sim-planner contact info:</h5>\r\n                    <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">Phone: +64 9 </p>\r\n                    <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">Email: <a");

WriteLiteral(" href=\"mailto:info@sim-planner.com\"");

WriteLiteral(" style=\"Margin: 0; color: #2199e8; font-family: Helvetica, Arial, sans-serif; fon" +
"t-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; tex" +
"t-decoration: none;\"");

WriteLiteral(">info@sim-planner.com</a></p>\r\n                </th></tr></table></th>\r\n         " +
"       <th");

WriteLiteral(" class=\"small-12 large-6 columns last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 8px; padding-right: 16px; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0;" +
" position: relative; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n                        <th");

WriteLiteral(" class=\"small-12 large-12 columns first\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                            Connect With Us:\r\n                        </th>\n<t" +
"h");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n                        <th");

WriteLiteral(" class=\"small-6 large-6 columns\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                            <table");

WriteLiteral(" class=\"button facebook tiny\"");

WriteLiteral(" style=\"Margin: 0 0 16px 0; border-collapse: collapse; border-spacing: 0; margin:" +
" 0 0 16px 0; padding: 0; text-align: left; vertical-align: top; width: auto;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #2199e8; background-color: #3b5998; border: 2px solid #2199e8; border-collapse: collapse !important; border-color: #3B5998; color: #fefefe; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 4px 8px 4px 8px; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><a");

WriteLiteral(" href=\"http://sim-planner.com\"");

WriteLiteral(@" style=""Margin: 0; border: 0 solid #2199e8; border-radius: 3px; color: #fefefe; display: inline-block; font-family: Helvetica, Arial, sans-serif; font-size: 10px; font-weight: normal; line-height: 1.3; margin: 0; padding: 4px 8px 4px 8px; text-align: left; text-decoration: none;""");

WriteLiteral(">Facebook</a></td></tr></table></td></tr></table>\r\n                        </th><" +
"/tr></table></th>\r\n                        <th");

WriteLiteral(" class=\"small-6 large-6 columns\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                            <table");

WriteLiteral(" class=\"button twitter tiny\"");

WriteLiteral(" style=\"Margin: 0 0 16px 0; border-collapse: collapse; border-spacing: 0; margin:" +
" 0 0 16px 0; padding: 0; text-align: left; vertical-align: top; width: auto;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #2199e8; background-color: #55acee; border: 2px solid #2199e8; border-collapse: collapse !important; border-color: #55acee; color: #fefefe; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 4px 8px 4px 8px; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><a");

WriteLiteral(" href=\"http://sim-planner.com\"");

WriteLiteral(@" style=""Margin: 0; border: 0 solid #2199e8; border-radius: 3px; color: #fefefe; display: inline-block; font-family: Helvetica, Arial, sans-serif; font-size: 10px; font-weight: normal; line-height: 1.3; margin: 0; padding: 4px 8px 4px 8px; text-align: left; text-decoration: none;""");

WriteLiteral(">Twitter</a></td></tr></table></td></tr></table>\r\n                        </th></" +
"tr></table></th>\r\n                        <th");

WriteLiteral(" class=\"small-6 large-6 columns\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                            <table");

WriteLiteral(" class=\"button google tiny\"");

WriteLiteral(" style=\"Margin: 0 0 16px 0; border-collapse: collapse; border-spacing: 0; margin:" +
" 0 0 16px 0; padding: 0; text-align: left; vertical-align: top; width: auto;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #2199e8; background-color: #dd4b39; border: 2px solid #2199e8; border-collapse: collapse !important; border-color: #dd4b39; color: #fefefe; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 4px 8px 4px 8px; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><a");

WriteLiteral(" href=\"http://sim-planner.com\"");

WriteLiteral(@" style=""Margin: 0; border: 0 solid #2199e8; border-radius: 3px; color: #fefefe; display: inline-block; font-family: Helvetica, Arial, sans-serif; font-size: 10px; font-weight: normal; line-height: 1.3; margin: 0; padding: 4px 8px 4px 8px; text-align: left; text-decoration: none;""");

WriteLiteral(">Google+</a></td></tr></table></td></tr></table>\r\n                        </th></" +
"tr></table></th>\r\n                        <th");

WriteLiteral(" class=\"small-6 large-6 columns last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                            <table");

WriteLiteral(" class=\"button linkedIn tiny\"");

WriteLiteral(" style=\"Margin: 0 0 16px 0; border-collapse: collapse; border-spacing: 0; margin:" +
" 0 0 16px 0; padding: 0; text-align: left; vertical-align: top; width: auto;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><td");

WriteLiteral(@" style=""-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; background: #2199e8; background-color: #007bb5; border: 2px solid #2199e8; border-collapse: collapse !important; border-color: #007bb5; color: #fefefe; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 4px 8px 4px 8px; text-align: left; vertical-align: top; word-wrap: break-word;""");

WriteLiteral("><a");

WriteLiteral(" href=\"http://sim-planner.com\"");

WriteLiteral(@" style=""Margin: 0; border: 0 solid #2199e8; border-radius: 3px; color: #fefefe; display: inline-block; font-family: Helvetica, Arial, sans-serif; font-size: 10px; font-weight: normal; line-height: 1.3; margin: 0; padding: 4px 8px 4px 8px; text-align: left; text-decoration: none;""");

WriteLiteral(">LinkedIn</a></td></tr></table></td></tr></table>\r\n                        </th><" +
"/tr></table></th>\r\n                    </tr></tbody></table>\r\n                </" +
"th></tr></table></th>\r\n            </tr></tbody></table>\r\n            <table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0;" +
" position: relative; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n                <th");

WriteLiteral(" class=\"small-12 large-5 columns first\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 8px; text-align: left; width: 225.66667px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                    whatever\r\n                </th></tr></table></th>\r\n       " +
"         <th");

WriteLiteral(" class=\"small-12 large-7 columns last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 8px; padding-right: 16px; text-align: left; width: 322.33333px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0;" +
" position: relative; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n                        <th");

WriteLiteral(" class=\"small-6 large-6 columns first\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">Hello</p>\r\n                        </th></tr></table></th>\r\n                    " +
"    <th");

WriteLiteral(" class=\"small-6 large-6 columns\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">Hello</p>\r\n                        </th></tr></table></th>\r\n                    " +
"    <th");

WriteLiteral(" class=\"small-6 large-6 columns\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">Hello</p>\r\n                        </th></tr></table></th>\r\n                    " +
"    <th");

WriteLiteral(" class=\"small-6 large-6 columns last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 0 !important; padding-right: 0 !important; text-align: left; width: 274px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(@">Hello</p>
                        </th></tr></table></th>
                    </tr></tbody></table>
                </th></tr></table></th>
            </tr></tbody></table>
        </td></tr></tbody></table>
    </td></tr></table>
    <!-- prevent Gmail on iOS font size manipulation -->
</body>
</html>

");

        }
    }
}
#pragma warning restore 1591
