#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Web.UserEmails
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
    using SP.DataAccess;
    
    #line default
    #line hidden
    
    #line 3 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
    using SP.Dto.Utilities;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class NotifyNewRegistrationRequest : SP.Web.UserEmails.EmailBase
    {
#line hidden
        #line 5 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
           
    public Participant PersonRequesting { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 8 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
  
    Layout = new SP.Web.UserEmails.LayoutTemplate
    {
        Title = "Registration Request"
    };

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n    <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"callout\"");

WriteLiteral(" style=\"Margin-bottom: 16px; border-collapse: collapse; border-spacing: 0; margin" +
"-bottom: 16px; padding: 0; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" class=\"callout-inner primary\"");

WriteLiteral(" style=\"Margin: 0; background: #def0fc; border: 1px solid #444444; color: #0a0a0a" +
"; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: norma" +
"l; line-height: 1.3; margin: 0; padding: 10px; text-align: left; width: 100%;\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 20px; font-weight: normal; line-height: 1.6; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">\r\n                A request has been submitted to register a new institution, de" +
"partment &amp; user - details below.\r\n            </p>\r\n        </th><th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table>\r\n    </th>\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n</tr></tbody></table>\r\n<table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n    <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 28px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left; word-wrap: normal;\"");

WriteLiteral(">\r\n            Institution\r\n        </h3>\r\n        <dl>\r\n            <dt>\r\n      " +
"          Name\r\n            </dt>\r\n            <dd>\r\n");

WriteLiteral("                ");

            
            #line 34 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
           Write(PersonRequesting.Department.Institution.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n            <dt>\r\n                Abbreviation\r\n            " +
"</dt>\r\n            <dd>\r\n");

WriteLiteral("                ");

            
            #line 40 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
           Write(PersonRequesting.Department.Institution.Abbreviation);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n            <dt>\r\n                Locale Code\r\n            <" +
"/dt>\r\n            <dd>\r\n");

WriteLiteral("                ");

            
            #line 46 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
           Write(PersonRequesting.Department.Institution.LocaleCode);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n            <dt>\r\n                Time Zone\r\n            </d" +
"t>\r\n            <dd>\r\n");

WriteLiteral("                ");

            
            #line 52 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
           Write(PersonRequesting.Department.Institution.TimeZone.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n");

            
            #line 54 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
            
            
            #line default
            #line hidden
            
            #line 54 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
             if (!string.IsNullOrEmpty(PersonRequesting.Department.Institution.HomepageUrl))
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt>\r\n                    URL\r\n                </dt>\r\n");

WriteLiteral("                <dd>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4877), Tuple.Create("\"", 4936)
            
            #line 60 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
, Tuple.Create(Tuple.Create("", 4884), Tuple.Create<System.Object, System.Int32>(PersonRequesting.Department.Institution.HomepageUrl
            
            #line default
            #line hidden
, 4884), false)
);

WriteLiteral(" style=\"Margin: 0; color: #2199e8; font-family: Helvetica, Arial, sans-serif; fon" +
"t-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; tex" +
"t-decoration: none;\"");

WriteLiteral(">");

            
            #line 60 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
                                                                                                                                                                                                                                                                   Write(PersonRequesting.Department.Institution.HomepageUrl);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    <small");

WriteLiteral(" style=\"color: #cacaca; font-size: 80%;\"");

WriteLiteral(">please examine URL carefully before clicking on the link</small>\r\n              " +
"  </dd>\r\n");

            
            #line 63 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 64 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
             if (PersonRequesting.Department.Institution.Latitude.HasValue && PersonRequesting.Department.Institution.Longitude.HasValue)
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt>\r\n                    Location\r\n                </dt>\r\n");

WriteLiteral("                <dd>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5621), Tuple.Create("\"", 5784)
, Tuple.Create(Tuple.Create("", 5628), Tuple.Create("https://www.google.com/maps/place/", 5628), true)
            
            #line 70 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
, Tuple.Create(Tuple.Create("", 5662), Tuple.Create<System.Object, System.Int32>(PersonRequesting.Department.Institution.Latitude.ToString()
            
            #line default
            #line hidden
, 5662), false)
, Tuple.Create(Tuple.Create("", 5722), Tuple.Create(",", 5722), true)
            
            #line 70 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
                                            , Tuple.Create(Tuple.Create("", 5723), Tuple.Create<System.Object, System.Int32>(PersonRequesting.Department.Institution.Longitude.ToString()
            
            #line default
            #line hidden
, 5723), false)
);

WriteLiteral(" style=\"Margin: 0; color: #2199e8; font-family: Helvetica, Arial, sans-serif; fon" +
"t-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; tex" +
"t-decoration: none;\"");

WriteLiteral(">Google Maps</a>\r\n                </dd>\r\n");

            
            #line 72 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 73 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
             if (!string.IsNullOrWhiteSpace(PersonRequesting.Department.Institution.LogoImageFileName))
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt>\r\n                    Logo\r\n                </dt>\r\n");

WriteLiteral("                <dd>\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6259), Tuple.Create("\"", 6384)
            
            #line 79 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
, Tuple.Create(Tuple.Create("", 6265), Tuple.Create<System.Object, System.Int32>(BaseInsecureUrl + '/' + IAssociateFileTools.ServerPathToUrl(PersonRequesting.Department.Institution.GetServerPath())
            
            #line default
            #line hidden
, 6265), false)
);

WriteLiteral(" width=\"200\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 6397), Tuple.Create("\"", 6457)
, Tuple.Create(Tuple.Create("", 6403), Tuple.Create("logo", 6403), true)
, Tuple.Create(Tuple.Create(" ", 6407), Tuple.Create("for", 6408), true)
            
            #line 79 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
                                                                                                , Tuple.Create(Tuple.Create(" ", 6411), Tuple.Create<System.Object, System.Int32>(PersonRequesting.Department.Institution.Name
            
            #line default
            #line hidden
, 6412), false)
);

WriteLiteral(" style=\"-ms-interpolation-mode: bicubic; clear: both; display: block; max-width: " +
"100%; outline: none; text-decoration: none; width: auto;\"");

WriteLiteral(">\r\n                </dd>\r\n");

            
            #line 81 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 82 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
             if (!string.IsNullOrWhiteSpace(PersonRequesting.Department.Institution.About))
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt>\r\n                    About\r\n                </dt>\r\n");

WriteLiteral("                <dd>\r\n");

WriteLiteral("                    ");

            
            #line 88 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
               Write(PersonRequesting.Department.Institution.About);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </dd>\r\n");

            
            #line 90 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </dl>\r\n    </th>\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n</tr></tbody></table>\r\n<table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n    <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 28px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left; word-wrap: normal;\"");

WriteLiteral(">\r\n            Department\r\n        </h3>\r\n        <dl>\r\n            <dt>\r\n       " +
"         Name\r\n            </dt>\r\n            <dd>\r\n");

WriteLiteral("                ");

            
            #line 105 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
           Write(PersonRequesting.Department.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n            <dt>\r\n                Abbreviation\r\n            " +
"</dt>\r\n            <dd>\r\n");

WriteLiteral("                ");

            
            #line 111 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
           Write(PersonRequesting.Department.Abbreviation);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n        </dl>\r\n    </th>\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n</tr></tbody></table>\r\n<table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n    <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 28px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left; word-wrap: normal;\"");

WriteLiteral(">\r\n            Proposed administrator\r\n        </h3>\r\n        <dl>\r\n            <" +
"dt>\r\n                Name\r\n            </dt>\r\n            <dd>\r\n");

WriteLiteral("                ");

            
            #line 127 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
           Write(PersonRequesting.FullName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n            <dt>\r\n                Email\r\n            </dt>\r\n" +
"            <dd>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 10555), Tuple.Create("\"", 10590)
            
            #line 133 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
, Tuple.Create(Tuple.Create("", 10562), Tuple.Create<System.Object, System.Int32>(GetMailTo(PersonRequesting)
            
            #line default
            #line hidden
, 10562), false)
);

WriteLiteral(" style=\"Margin: 0; color: #2199e8; font-family: Helvetica, Arial, sans-serif; fon" +
"t-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; tex" +
"t-decoration: none;\"");

WriteLiteral(">");

            
            #line 133 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
                                                                                                                                                                                                                                       Write(PersonRequesting.Email);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 133 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
                                                                                                                                                                                                                                                               Write(PersonRequesting.AlternateEmail);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            </dd>\r\n");

            
            #line 135 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
            
            
            #line default
            #line hidden
            
            #line 135 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
             if (!string.IsNullOrEmpty(PersonRequesting.PhoneNumber))
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt>\r\n                    Phone Number\r\n                </dt>\r\n");

WriteLiteral("                <dd>\r\n");

WriteLiteral("                    ");

            
            #line 141 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
               Write(PersonRequesting.PhoneNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </dd>\r\n");

            
            #line 143 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <dt>\r\n                Professional Role\r\n            </dt>\r\n         " +
"   <dd>\r\n                <strong>");

            
            #line 148 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
                   Write(PersonRequesting.ProfessionalRole.Category.ToString());

            
            #line default
            #line hidden
WriteLiteral("</strong> - ");

            
            #line 148 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
                                                                                     Write(PersonRequesting.ProfessionalRole.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n        </dl>\r\n        \r\n    </th>\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n</tr></tbody></table>\r\n<table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n    <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <hr>\r\n        <table");

WriteLiteral(" class=\"callout\"");

WriteLiteral(" style=\"Margin-bottom: 16px; border-collapse: collapse; border-spacing: 0; margin" +
"-bottom: 16px; padding: 0; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" class=\"callout-inner secondary\"");

WriteLiteral(" style=\"Margin: 0; background: #ebebeb; border: 1px solid #444444; color: #0a0a0a" +
"; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: norma" +
"l; line-height: 1.3; margin: 0; padding: 10px; text-align: left; width: 100%;\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">\r\n                In order to approve or delete this request, please go to the <" +
"a");

WriteAttribute("href", Tuple.Create(" href=\"", 13468), Tuple.Create("\"", 13566)
            
            #line 160 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
     , Tuple.Create(Tuple.Create("", 13475), Tuple.Create<System.Object, System.Int32>(BaseUrl
            
            #line default
            #line hidden
, 13475), false)
, Tuple.Create(Tuple.Create("", 13483), Tuple.Create("/#/reviewRegistrationRequest/", 13483), true)
            
            #line 160 "..\..\UserEmails\NotifyNewRegistrationRequest.cshtml"
                                          , Tuple.Create(Tuple.Create("", 13512), Tuple.Create<System.Object, System.Int32>(PersonRequesting.Department.Institution.Id.ToString()
            
            #line default
            #line hidden
, 13512), false)
);

WriteLiteral(" style=\"Margin: 0; color: #2199e8; font-family: Helvetica, Arial, sans-serif; fon" +
"t-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; tex" +
"t-decoration: none;\"");

WriteLiteral(">Review Registration Requests</a> page (will require login details).\r\n           " +
" </p>\r\n        </th><th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table>\r\n    </th>\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n</tr></tbody></table>");

        }
    }
}
#pragma warning restore 1591
