#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Web.UserEmails
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\UserEmails\NotifyBooking.cshtml"
    using SP.DataAccess;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class NotifyBooking : SP.Web.UserEmails.EmailBase
    {
#line hidden
        #line 4 "..\..\UserEmails\NotifyBooking.cshtml"
           
    public Participant PersonBooking { get; set; }
    public Room RoomBooked { get; set; }
    public Room RoomCancelled { get; set; }
    public Course Course { get; set; }
    public IEnumerable<Manikin> ManikinsBooked { get; set; }
    public IEnumerable<Manikin> ManikinsCancelled { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 12 "..\..\UserEmails\NotifyBooking.cshtml"
   
    Layout = new SP.Web.UserEmails.LayoutTemplate {
        Title = "Booking Request"
    };
    if (ManikinsBooked == null)
    {
        ManikinsBooked = new Manikin[0];
    }
    if (ManikinsCancelled == null)
    {
        ManikinsCancelled = new Manikin[0];
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n    <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"callout\"");

WriteLiteral(" style=\"Margin-bottom: 16px; border-collapse: collapse; border-spacing: 0; margin" +
"-bottom: 16px; padding: 0; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" class=\"callout-inner info\"");

WriteLiteral(" style=\"Margin: 0; background: #fefefe; border: 1px solid #cbcbcb; color: #0a0a0a" +
"; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: norma" +
"l; line-height: 1.3; margin: 0; padding: 10px; text-align: left; width: 100%;\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2472), Tuple.Create("\"", 2504)
            
            #line 29 "..\..\UserEmails\NotifyBooking.cshtml"
, Tuple.Create(Tuple.Create("", 2479), Tuple.Create<System.Object, System.Int32>(GetMailTo(PersonBooking)
            
            #line default
            #line hidden
, 2479), false)
);

WriteLiteral(" style=\"Margin: 0; color: #2199e8; font-family: Helvetica, Arial, sans-serif; fon" +
"t-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; tex" +
"t-decoration: none;\"");

WriteLiteral(">");

            
            #line 29 "..\..\UserEmails\NotifyBooking.cshtml"
                                                                                                                                                                                                                                    Write(PersonBooking.FullName);

            
            #line default
            #line hidden
WriteLiteral("</a> has\r\n");

            
            #line 30 "..\..\UserEmails\NotifyBooking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 30 "..\..\UserEmails\NotifyBooking.cshtml"
                 if (RoomBooked != null || ManikinsBooked.Any()) {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("requested use of\r\n");

            
            #line 32 "..\..\UserEmails\NotifyBooking.cshtml"
                } else {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("<em>cancelled</em> the request for \r\n");

            
            #line 34 "..\..\UserEmails\NotifyBooking.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                the following\r\n                <strong>\r\n");

            
            #line 37 "..\..\UserEmails\NotifyBooking.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 37 "..\..\UserEmails\NotifyBooking.cshtml"
                     if (RoomBooked != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("room\r\n");

            
            #line 40 "..\..\UserEmails\NotifyBooking.cshtml"
                        if (ManikinsBooked.Any())
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("and\r\n");

            
            #line 43 "..\..\UserEmails\NotifyBooking.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 45 "..\..\UserEmails\NotifyBooking.cshtml"
                     if (ManikinsBooked.Any())
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("manikin(s)\r\n");

            
            #line 48 "..\..\UserEmails\NotifyBooking.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </strong>\r\n                on the ");

            
            #line 50 "..\..\UserEmails\NotifyBooking.cshtml"
                  Write(Course.StartLocal.ToString("g", Course.Department.Institution.Culture.CultureInfo));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" class=\"aside\"");

WriteLiteral(">\r\n                    finishing ");

            
            #line 52 "..\..\UserEmails\NotifyBooking.cshtml"
                         Write(Course.FinishCourseLocal().ToString("g", Course.Department.Institution.Culture.CultureInfo));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n            </p>\r\n        </th><th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table>\r\n    </th>\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n</tr></tbody></table>\r\n<table");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; position: relat" +
"ive; text-align: left; vertical-align: top; width: 100%;\"");

WriteLiteral("><tbody><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral(">\r\n    <th");

WriteLiteral(" class=\"small-12 large-12 columns first last\"");

WriteLiteral(@" style=""Margin: 0 auto; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; padding-bottom: 16px; padding-left: 16px; padding-right: 16px; text-align: left; width: 564px;""");

WriteLiteral("><table");

WriteLiteral(" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: lef" +
"t; vertical-align: top; width: 100%;\"");

WriteLiteral("><tr");

WriteLiteral(" style=\"padding: 0; text-align: left; vertical-align: top;\"");

WriteLiteral("><th");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text" +
"-align: left;\"");

WriteLiteral(">\r\n");

            
            #line 61 "..\..\UserEmails\NotifyBooking.cshtml"
        
            
            #line default
            #line hidden
            
            #line 61 "..\..\UserEmails\NotifyBooking.cshtml"
         if (ManikinsBooked.Any() || RoomBooked != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">\r\n                The booking is assumed active unless you cancel.\r\n            " +
"</p>\r\n");

WriteLiteral("            <h4");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 24px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left; word-wrap: normal;\"");

WriteLiteral(">\r\n                Details:\r\n            </h4>\r\n");

WriteLiteral("            <ul>\r\n");

            
            #line 70 "..\..\UserEmails\NotifyBooking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 70 "..\..\UserEmails\NotifyBooking.cshtml"
                 if (RoomBooked != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 73 "..\..\UserEmails\NotifyBooking.cshtml"
                   Write(RoomBooked.ShortDescription);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 75 "..\..\UserEmails\NotifyBooking.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 77 "..\..\UserEmails\NotifyBooking.cshtml"
                 foreach (var m in ManikinsBooked)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 80 "..\..\UserEmails\NotifyBooking.cshtml"
                   Write(m.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 82 "..\..\UserEmails\NotifyBooking.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");

WriteLiteral("            <p");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left;\"");

WriteLiteral(">\r\n                TODO - place button here to goto cancel bookings page\r\n       " +
"     </p>\r\n");

            
            #line 87 "..\..\UserEmails\NotifyBooking.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 88 "..\..\UserEmails\NotifyBooking.cshtml"
         if (ManikinsCancelled.Any() || RoomCancelled != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <hr>\r\n");

WriteLiteral("            <h5");

WriteLiteral(" style=\"Margin: 0; Margin-bottom: 10px; color: inherit; font-family: Helvetica, A" +
"rial, sans-serif; font-size: 20px; font-weight: normal; line-height: 1.3; margin" +
": 0; margin-bottom: 10px; padding: 0; text-align: left; word-wrap: normal;\"");

WriteLiteral(">\r\n                The following bookings have been cancelled\r\n            </h5>\r" +
"\n");

WriteLiteral("            <ul>\r\n");

            
            #line 95 "..\..\UserEmails\NotifyBooking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 95 "..\..\UserEmails\NotifyBooking.cshtml"
                 if (RoomBooked != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 98 "..\..\UserEmails\NotifyBooking.cshtml"
                   Write(RoomBooked.ShortDescription);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 100 "..\..\UserEmails\NotifyBooking.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 102 "..\..\UserEmails\NotifyBooking.cshtml"
                 foreach (var m in ManikinsBooked)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 105 "..\..\UserEmails\NotifyBooking.cshtml"
                   Write(m.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 107 "..\..\UserEmails\NotifyBooking.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");

            
            #line 109 "..\..\UserEmails\NotifyBooking.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </th>\n<th");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" style=\"Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; fon" +
"t-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0 !impo" +
"rtant; text-align: left; visibility: hidden; width: 0;\"");

WriteLiteral("></th></tr></table></th>\r\n</tr></tbody></table>");

        }
    }
}
#pragma warning restore 1591
