#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Web.Scripts
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Scripts\AuthConfirmationResult.cshtml"
    using SP.DataAccess;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class AuthConfirmationResult : SP.Web.UserEmails.CourseParticipantEmailBase
    {
#line hidden
        #line 5 "..\..\Scripts\AuthConfirmationResult.cshtml"
           
    public Participant Auth { get; set; }
    public bool IsChanged { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 9 "..\..\Scripts\AuthConfirmationResult.cshtml"
   Layout = new SP.Web.UserEmails.LayoutTemplate { Title = "Course Invitation" }; 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<callout");

WriteLiteral(" class=\"primary\"");

WriteLiteral(">\r\n    <row>\r\n        <columns>\r\n            <p>");

            
            #line 14 "..\..\Scripts\AuthConfirmationResult.cshtml"
          Write(Auth.FullName);

            
            #line default
            #line hidden
WriteLiteral(" has <strong>");

            
            #line 14 "..\..\Scripts\AuthConfirmationResult.cshtml"
                                      Write(IsChanged?"accepted":"declined");

            
            #line default
            #line hidden
WriteLiteral("</strong> your request to change confirmation status.</p>\r\n            <p>\r\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Scripts\AuthConfirmationResult.cshtml"
           Write(CourseParticipant.Participant.FullName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 16 "..\..\Scripts\AuthConfirmationResult.cshtml"
                                                    Write(IsChanged?"is now":"remains");

            
            #line default
            #line hidden
WriteLiteral(" registered as \r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Scripts\AuthConfirmationResult.cshtml"
            Write(CourseParticipant.IsConfirmed.Value?"attending":"not attending");

            
            #line default
            #line hidden
WriteLiteral(".\r\n            </p>\r\n        </columns>\r\n    </row>\r\n</callout>\r\n\r\n\r\n");

            
            #line 24 "..\..\Scripts\AuthConfirmationResult.cshtml"
 if(!IsChanged) { 

            
            #line default
            #line hidden
WriteLiteral("    <row>\r\n        <columns>\r\n            <p>If you would like to discuss this fu" +
"rther, you may wish to contact one of the organiser(s) below:</p>\r\n            <" +
"ul>\r\n");

            
            #line 29 "..\..\Scripts\AuthConfirmationResult.cshtml"
                
            
            #line default
            #line hidden
            
            #line 29 "..\..\Scripts\AuthConfirmationResult.cshtml"
                 foreach(var o in (from cp in CourseParticipant.Course.CourseParticipants where cp.IsOrganiser select cp.Participant)){

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1242), Tuple.Create("\"", 1266)
, Tuple.Create(Tuple.Create("", 1249), Tuple.Create("mailto:", 1249), true)
            
            #line 31 "..\..\Scripts\AuthConfirmationResult.cshtml"
, Tuple.Create(Tuple.Create("", 1256), Tuple.Create<System.Object, System.Int32>(o.Email
            
            #line default
            #line hidden
, 1256), false)
);

WriteLiteral(">");

            
            #line 31 "..\..\Scripts\AuthConfirmationResult.cshtml"
                                               Write(o.FullName);

            
            #line default
            #line hidden
WriteLiteral("</a> Tel: ");

            
            #line 31 "..\..\Scripts\AuthConfirmationResult.cshtml"
                                                                    Write(o.PhoneNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 33 "..\..\Scripts\AuthConfirmationResult.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </columns>\r\n    </row>\r\n");

            
            #line 37 "..\..\Scripts\AuthConfirmationResult.cshtml"
}
            
            #line default
            #line hidden
WriteLiteral(" ");

        }
    }
}
#pragma warning restore 1591
