#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Web.UserEmails.Inky
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
    using SP.DataAccess;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class MultiCourseInvite : SP.Web.UserEmails.EmailBase
    {
#line hidden
        #line 4 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
           
    public Participant PersonRequesting { get; set; }
    public Participant Recipient { get; set; }
    public IEnumerable<Course> Courses { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 9 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
  
    Layout = new SP.Web.UserEmails.LayoutTemplate
    {
        Title = "Upcoming Courses"
    };
    FormatProvider = Recipient.Department.Institution.Culture.CultureInfo;

            
            #line default
            #line hidden
WriteLiteral("\r\n<row>\r\n    <columns");

WriteLiteral(" large=\"12\"");

WriteLiteral(">\r\n        <callout");

WriteLiteral(" class=\"primary\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 628), Tuple.Create("\"", 663)
            
            #line 20 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
, Tuple.Create(Tuple.Create("", 635), Tuple.Create<System.Object, System.Int32>(GetMailTo(PersonRequesting)
            
            #line default
            #line hidden
, 635), false)
);

WriteLiteral(">");

            
            #line 20 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
                                                  Write(PersonRequesting.FullName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                (");

            
            #line 21 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
            Write(PersonRequesting.Department.Abbreviation);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 21 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
                                                      Write(PersonRequesting.ProfessionalRole.Description);

            
            #line default
            #line hidden
WriteLiteral(@")
                is looking for faculty to help run the courses as listed below.
            </p>
        </callout>
    </columns>
</row>
<row>
    <columns>
        <table>
            <thead>
                <tr>
                    <th>
                        Date
                    </th>
                    <th>
                        Course Type
                    </th>
                    <th>
                        Required Faculty
                    </th>
                </tr>
            </thead>
            <tbody>
");

            
            #line 44 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
                
            
            #line default
            #line hidden
            
            #line 44 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
                 foreach (var c in Courses)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 48 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
                       Write(string.Format(FormatProvider, "{0:d} {0:t}", c.StartLocal));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 51 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
                       Write(c.CourseFormat.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            (");

            
            #line 52 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
                        Write(c.CourseFormat.CourseType.Description);

            
            #line default
            #line hidden
WriteLiteral(")\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 55 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
                        Write(c.FacultyNoRequired - c.CourseParticipants.Count(cp => cp.IsFaculty && cp.IsConfirmed != false) );

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");

            
            #line 58 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </columns>\r\n</row>\r\n<row>\r\n    <colum" +
"ns");

WriteLiteral(" large=\"12\"");

WriteLiteral(">\r\n        <p>\r\n            If you are able to help by attending as faculty, plea" +
"se log in to <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2218), Tuple.Create("\"", 2251)
            
            #line 66 "..\..\UserEmails\Inky\MultiCourseInvite.cshtml"
       , Tuple.Create(Tuple.Create("", 2225), Tuple.Create<System.Object, System.Int32>(BaseUrl
            
            #line default
            #line hidden
, 2225), false)
, Tuple.Create(Tuple.Create("", 2233), Tuple.Create("/#/myCourseInvites", 2233), true)
);

WriteLiteral(" >Sim Planner Course Invitations</a> \r\n            and select which course(s) you" +
" can attend. \r\n        </p>\r\n        <p>\r\n            Thank you.\r\n        </p>\r\n" +
"    </columns>\r\n</row>");

        }
    }
}
#pragma warning restore 1591
