#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Web.UserEmails.Inky
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
    using SP.DataAccess;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class MultiCourseInviteResonse : SP.Web.UserEmails.EmailBase
    {
#line hidden
        #line 4 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
           
    public Participant PersonResponding { get; set; }
    public IEnumerable<Course> Courses { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 8 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
  
    Layout = new SP.Web.UserEmails.LayoutTemplate
    {
        Title = "Invitation Response"
    };
    FormatProvider = Courses.First().Department.Institution.Culture.CultureInfo;

            
            #line default
            #line hidden
WriteLiteral("\r\n<row>\r\n    <columns");

WriteLiteral(" large=\"12\"");

WriteLiteral(">\r\n        <callout");

WriteLiteral(" class=\"primary\"");

WriteLiteral(">\r\n            <p>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 576), Tuple.Create("\"", 611)
            
            #line 19 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
, Tuple.Create(Tuple.Create("", 583), Tuple.Create<System.Object, System.Int32>(GetMailTo(PersonResponding)
            
            #line default
            #line hidden
, 583), false)
);

WriteLiteral(">");

            
            #line 19 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                                                  Write(PersonResponding.FullName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                <small>(");

            
            #line 20 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                   Write(PersonResponding.Department.Abbreviation);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 20 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                                                             Write(PersonResponding.ProfessionalRole.Description);

            
            #line default
            #line hidden
WriteLiteral(@")</small>
                has responded to your invitation.
            </p>
        </callout>
        <p>
            Listed below are your upcoming courses
        </p>
    </columns>
</row>
<row>
    <columns>
        <table>
            <thead>
                <tr>
                    <th>
                        Date
                    </th>
                    <th>
                        Course
                    </th>
                    <th>
                        Reqd.
                    </th>
                    <th>
");

WriteLiteral("                        ");

            
            #line 44 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                   Write(PersonResponding.FullName.Substring(0,PersonResponding.FullName.IndexOf(' ')));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </th>\r\n                </tr>\r\n            </thead>\r\n       " +
"     <tbody>\r\n");

            
            #line 49 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                
            
            #line default
            #line hidden
            
            #line 49 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                 foreach (var c in Courses)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 53 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                       Write(string.Format(FormatProvider, "{0:d} {0:t}", c.StartLocal));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 56 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                       Write(c.CourseFormat.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            (");

            
            #line 57 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                        Write(c.CourseFormat.CourseType.Description);

            
            #line default
            #line hidden
WriteLiteral(")\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 60 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                        Write(c.CourseParticipants.Count(cp => cp.IsFaculty && cp.IsConfirmed != false));

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 60 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                                                                                                     Write(c.FacultyNoRequired);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

            
            #line 63 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 63 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                             if (c.CourseParticipants.Any(cp=>cp.ParticipantId == PersonResponding.Id))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"label success round\"");

WriteLiteral(">&#x2713;</span>\r\n");

            
            #line 66 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n                    </tr>\r\n");

            
            #line 69 "..\..\UserEmails\Inky\MultiCourseInviteResonse.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </columns>\r\n</row>");

        }
    }
}
#pragma warning restore 1591
