#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Web.UserEmails.Inky
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
    using SP.DataAccess;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class NotifyBooking : SP.Web.UserEmails.EmailBase
    {
#line hidden
        #line 4 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
           
    public Participant PersonBooking { get; set; }
    public Room RoomBooked { get; set; }
    public Room RoomCancelled { get; set; }
    public Course Course { get; set; }
    public IEnumerable<Manikin> ManikinsBooked { get; set; }
    public IEnumerable<Manikin> ManikinsCancelled { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 12 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
   
    Layout = new SP.Web.UserEmails.LayoutTemplate {
        Title = "Booking Request"
    };
    if (ManikinsBooked == null)
    {
        ManikinsBooked = new Manikin[0];
    }
    if (ManikinsCancelled == null)
    {
        ManikinsCancelled = new Manikin[0];
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<row>\r\n    <columns");

WriteLiteral(" large=\"12\"");

WriteLiteral(">\r\n        <callout");

WriteLiteral(" class=\"info\"");

WriteLiteral(">\r\n            <p>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 881), Tuple.Create("\"", 913)
            
            #line 29 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
, Tuple.Create(Tuple.Create("", 888), Tuple.Create<System.Object, System.Int32>(GetMailTo(PersonBooking)
            
            #line default
            #line hidden
, 888), false)
);

WriteLiteral(">");

            
            #line 29 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                                               Write(PersonBooking.FullName);

            
            #line default
            #line hidden
WriteLiteral("</a> has\r\n");

            
            #line 30 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 30 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                 if (RoomBooked != null || ManikinsBooked.Any()) {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("requested use of\r\n");

            
            #line 32 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                } else {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("<em>cancelled</em> the request for \r\n");

            
            #line 34 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                the following\r\n                <strong>\r\n");

            
            #line 37 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 37 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                     if (RoomBooked != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("room\r\n");

            
            #line 40 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                        if (ManikinsBooked.Any())
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("and\r\n");

            
            #line 43 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 45 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                     if (ManikinsBooked.Any())
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("manikin(s)\r\n");

            
            #line 48 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </strong>\r\n                on the ");

            
            #line 50 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                  Write(Course.StartFacultyLocal.ToString("g", Course.Department.Institution.Culture.CultureInfo));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" class=\"aside\"");

WriteLiteral(">\r\n                    finishing ");

            
            #line 52 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                         Write(Course.FinishCourseFacultyLocal().ToString("g", Course.Department.Institution.Culture.CultureInfo));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n            </p>\r\n        </callout>\r\n    </columns>\r\n" +
"</row>\r\n<row>\r\n    <columns");

WriteLiteral(" large=\"12\"");

WriteLiteral(">\r\n");

            
            #line 60 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
        
            
            #line default
            #line hidden
            
            #line 60 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
         if (ManikinsBooked.Any() || RoomBooked != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>\r\n                The booking is assumed active unless you cancel." +
"\r\n            </p>\r\n");

WriteLiteral("            <h4>\r\n                Details:\r\n            </h4>\r\n");

WriteLiteral("            <ul>\r\n");

            
            #line 69 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 69 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                 if (RoomBooked != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 72 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                   Write(RoomBooked.ShortDescription);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 74 "..\..\UserEmails\Inky\NotifyBooking.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 76 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                 foreach (var m in ManikinsBooked)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 79 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                   Write(m.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 81 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");

WriteLiteral("            <p>\r\n                TODO - place button here to goto cancel bookings" +
" page\r\n            </p>\r\n");

            
            #line 86 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 87 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
         if (ManikinsCancelled.Any() || RoomCancelled != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <hr />\r\n");

WriteLiteral("            <h5>\r\n                The following bookings have been cancelled\r\n   " +
"         </h5>\r\n");

WriteLiteral("            <ul>\r\n");

            
            #line 94 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 94 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                 if (RoomBooked != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 97 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                   Write(RoomBooked.ShortDescription);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 99 "..\..\UserEmails\Inky\NotifyBooking.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 101 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                 foreach (var m in ManikinsBooked)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 104 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                   Write(m.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 106 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");

            
            #line 108 "..\..\UserEmails\Inky\NotifyBooking.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </columns>\r\n</row>\r\n");

        }
    }
}
#pragma warning restore 1591
