; Object.defineProperty(window, 'medsimMetadata', {enumerable: false, configurable: false, writable: false,value: JSON.stringify({
  "metadataVersion": "1.0.5",
  "namingConvention": "noChange",
  "localQueryComparisonOptions": "caseInsensitiveSQL",
  "dataServices": [],
  "structuralTypes": [
    {
      "shortName": "CountryDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "Countries",
      "dataProperties": [
        {
          "name": "Code",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "isPartOfKey": true,
          "maxLength": 2,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "stringLength",
              "minLength": 2,
              "maxLength": 2
            }
          ]
        },
        {
          "name": "Name",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 50,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 50,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "DialCode",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 3,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "name": "stringLength",
              "minLength": 2,
              "maxLength": 3
            },
            {
              "name": "regularExpression",
              "expression": "\\d+"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "CountryLocales",
          "entityTypeName": "CountryLocaleCodeDto:#SM.Dto",
          "isScalar": false,
          "associationName": "CountryDto_CountryLocales",
          "invForeignKeyNames": [
            "CountryCode"
          ]
        },
        {
          "name": "Hospitals",
          "entityTypeName": "InstitutionDto:#SM.Dto",
          "isScalar": false,
          "associationName": "InstitutionDto_Country",
          "invForeignKeyNames": [
            "CountryCode"
          ]
        }
      ]
    },
    {
      "shortName": "CountryLocaleCodeDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "CountryLocales",
      "dataProperties": [
        {
          "name": "CountryCode",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "isPartOfKey": true,
          "maxLength": 2,
          "validators": [
            {
              "name": "required"
            },
            {
              "maxLength": 2,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "LocaleCode",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "isPartOfKey": true,
          "maxLength": 5,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "stringLength",
              "minLength": 5,
              "maxLength": 5
            },
            {
              "name": "regularExpression",
              "expression": "[a-z]{2}-[A-Z]{2}"
            }
          ]
        },
        {
          "name": "Preference",
          "dataType": "Byte",
          "isNullable": false,
          "defaultValue": 0,
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": 0,
              "max": 255,
              "name": "byte"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "Country",
          "entityTypeName": "CountryDto:#SM.Dto",
          "isScalar": true,
          "associationName": "CountryDto_CountryLocales",
          "foreignKeyNames": [
            "CountryCode"
          ]
        }
      ]
    },
    {
      "shortName": "InstitutionDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "Institutions",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Name",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 50,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 50,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "About",
          "dataType": "String",
          "validators": [
            {
              "name": "string"
            }
          ]
        },
        {
          "name": "CountryCode",
          "dataType": "String",
          "maxLength": 2,
          "validators": [
            {
              "name": "stringLength",
              "minLength": 2,
              "maxLength": 2
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "Country",
          "entityTypeName": "CountryDto:#SM.Dto",
          "isScalar": true,
          "associationName": "InstitutionDto_Country",
          "foreignKeyNames": [
            "CountryCode"
          ]
        },
        {
          "name": "Departments",
          "entityTypeName": "DepartmentDto:#SM.Dto",
          "isScalar": false,
          "associationName": "InstitutionDto_Departments",
          "invForeignKeyNames": [
            "InstitutionId"
          ]
        }
      ]
    },
    {
      "shortName": "DepartmentDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "Departments",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Name",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 64,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 64,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "Abbreviation",
          "dataType": "String",
          "maxLength": 16,
          "validators": [
            {
              "maxLength": 16,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "InstitutionId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "InvitationLetterFilename",
          "dataType": "String",
          "maxLength": 256,
          "validators": [
            {
              "maxLength": 256,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "CertificateFilename",
          "dataType": "String",
          "maxLength": 256,
          "validators": [
            {
              "maxLength": 256,
              "name": "maxLength"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "CourseParticipants",
          "entityTypeName": "CourseParticipantDto:#SM.Dto",
          "isScalar": false,
          "associationName": "DepartmentDto_CourseParticipants",
          "invForeignKeyNames": [
            "DepartmentId"
          ]
        },
        {
          "name": "Courses",
          "entityTypeName": "CourseDto:#SM.Dto",
          "isScalar": false,
          "associationName": "DepartmentDto_Courses",
          "invForeignKeyNames": [
            "OutreachingDepartmentId"
          ]
        },
        {
          "name": "Institution",
          "entityTypeName": "InstitutionDto:#SM.Dto",
          "isScalar": true,
          "associationName": "InstitutionDto_Departments",
          "foreignKeyNames": [
            "InstitutionId"
          ]
        },
        {
          "name": "Manequins",
          "entityTypeName": "ManequinDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ManequinDto_Department"
        },
        {
          "name": "Participants",
          "entityTypeName": "ParticipantDto:#SM.Dto",
          "isScalar": false,
          "associationName": "DepartmentDto_Participants",
          "invForeignKeyNames": [
            "DefaultDepartmentId"
          ]
        },
        {
          "name": "Rooms",
          "entityTypeName": "RoomDto:#SM.Dto",
          "isScalar": false,
          "associationName": "DepartmentDto_Rooms",
          "invForeignKeyNames": [
            "DepartmentId"
          ]
        },
        {
          "name": "Scenarios",
          "entityTypeName": "ScenarioDto:#SM.Dto",
          "isScalar": false,
          "associationName": "DepartmentDto_Scenarios",
          "invForeignKeyNames": [
            "DepartmentId"
          ]
        }
      ]
    },
    {
      "shortName": "CourseParticipantDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "CourseParticipants",
      "dataProperties": [
        {
          "name": "CourseId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "ParticipantId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "IsConfirmed",
          "dataType": "Boolean",
          "isNullable": false,
          "defaultValue": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "bool"
            }
          ]
        },
        {
          "name": "IsFaculty",
          "dataType": "Boolean",
          "isNullable": false,
          "defaultValue": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "bool"
            }
          ]
        },
        {
          "name": "IsOrganiser",
          "dataType": "Boolean",
          "isNullable": false,
          "defaultValue": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "bool"
            }
          ]
        },
        {
          "name": "DepartmentId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "ProfessionalRoleId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "Course",
          "entityTypeName": "CourseDto:#SM.Dto",
          "isScalar": true,
          "associationName": "CourseDto_CourseParticipants",
          "foreignKeyNames": [
            "CourseId"
          ]
        },
        {
          "name": "Department",
          "entityTypeName": "DepartmentDto:#SM.Dto",
          "isScalar": true,
          "associationName": "DepartmentDto_CourseParticipants",
          "foreignKeyNames": [
            "DepartmentId"
          ]
        },
        {
          "name": "Participant",
          "entityTypeName": "ParticipantDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ParticipantDto_CourseParticipants",
          "foreignKeyNames": [
            "ParticipantId"
          ]
        },
        {
          "name": "ProfessionalRole",
          "entityTypeName": "ProfessionalRoleDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ProfessionalRoleDto_CourseParticipants",
          "foreignKeyNames": [
            "ProfessionalRoleId"
          ]
        }
      ]
    },
    {
      "shortName": "CourseDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "Courses",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "StartTime",
          "dataType": "DateTime",
          "isNullable": false,
          "defaultValue": "1899-12-31T-13:00:00.000Z",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "date"
            }
          ]
        },
        {
          "name": "DepartmentId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "OutreachingDepartmentId",
          "dataType": "Guid",
          "validators": [
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "RoomId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "FacultyNoRequired",
          "dataType": "Byte",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": 0,
              "max": 255,
              "name": "byte"
            }
          ]
        },
        {
          "name": "CourseTypeId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "ParticipantVideoFilename",
          "dataType": "String",
          "maxLength": 256,
          "validators": [
            {
              "maxLength": 256,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "FeedbackSummaryFilename",
          "dataType": "String",
          "maxLength": 256,
          "validators": [
            {
              "maxLength": 256,
              "name": "maxLength"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "CourseParticipants",
          "entityTypeName": "CourseParticipantDto:#SM.Dto",
          "isScalar": false,
          "associationName": "CourseDto_CourseParticipants",
          "invForeignKeyNames": [
            "CourseId"
          ]
        },
        {
          "name": "CourseType",
          "entityTypeName": "CourseTypeDto:#SM.Dto",
          "isScalar": true,
          "associationName": "CourseTypeDto_Courses",
          "foreignKeyNames": [
            "CourseTypeId"
          ]
        },
        {
          "name": "Department",
          "entityTypeName": "DepartmentDto:#SM.Dto",
          "isScalar": true,
          "associationName": "CourseDto_Department",
          "foreignKeyNames": [
            "DepartmentId"
          ]
        },
        {
          "name": "OutreachingDepartment",
          "entityTypeName": "DepartmentDto:#SM.Dto",
          "isScalar": true,
          "associationName": "DepartmentDto_Courses",
          "foreignKeyNames": [
            "OutreachingDepartmentId"
          ]
        },
        {
          "name": "Room",
          "entityTypeName": "RoomDto:#SM.Dto",
          "isScalar": true,
          "associationName": "RoomDto_Courses",
          "foreignKeyNames": [
            "RoomId"
          ]
        },
        {
          "name": "ScenarioFacultyRoles",
          "entityTypeName": "ScenarioFacultyRoleDto:#SM.Dto",
          "isScalar": false,
          "associationName": "CourseDto_ScenarioFacultyRoles",
          "invForeignKeyNames": [
            "CourseId"
          ]
        }
      ]
    },
    {
      "shortName": "CourseTypeDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "CourseTypes",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Description",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 50,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 50,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "IsInstructorCourse",
          "dataType": "Boolean",
          "isNullable": false,
          "defaultValue": false,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "bool"
            }
          ]
        },
        {
          "name": "DaysDuration",
          "dataType": "Byte",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": 0,
              "max": 255,
              "name": "byte"
            }
          ]
        },
        {
          "name": "EmersionCategory",
          "dataType": "String",
          "validators": [
            {
              "name": "string"
            }
          ],
          "enumType": "Edm.Self.Emersion"
        },
        {
          "name": "Abbrev",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 32,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 32,
              "name": "maxLength"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "Courses",
          "entityTypeName": "CourseDto:#SM.Dto",
          "isScalar": false,
          "associationName": "CourseTypeDto_Courses",
          "invForeignKeyNames": [
            "CourseTypeId"
          ]
        },
        {
          "name": "Scenarios",
          "entityTypeName": "ScenarioDto:#SM.Dto",
          "isScalar": false,
          "associationName": "CourseTypeDto_Scenarios",
          "invForeignKeyNames": [
            "CourseTypeId"
          ]
        }
      ]
    },
    {
      "shortName": "CourseSlotDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "CourseEvents",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Name",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 50,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 50,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "MinimumFaculty",
          "dataType": "Byte",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": 0,
              "max": 255,
              "name": "byte"
            }
          ]
        },
        {
          "name": "MaximumFaculty",
          "dataType": "Byte",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": 0,
              "max": 255,
              "name": "byte"
            }
          ]
        },
        {
          "name": "MinutesDuration",
          "dataType": "Int32",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": -2147483648,
              "max": 2147483647,
              "name": "int32"
            },
            {
              "name": "range",
              "min": 1,
              "max": 240
            }
          ]
        },
        {
          "name": "Day",
          "dataType": "Byte",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": 0,
              "max": 255,
              "name": "byte"
            }
          ]
        },
        {
          "name": "Order",
          "dataType": "Int32",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": -2147483648,
              "max": 2147483647,
              "name": "int32"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "DefaultResources",
          "entityTypeName": "CourseTeachingResourceDto:#SM.Dto",
          "isScalar": false,
          "associationName": "CourseSlotDto_DefaultResources",
          "invForeignKeyNames": [
            "CourseSlotId"
          ]
        }
      ]
    },
    {
      "shortName": "CourseTeachingResourceDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "CourseTeachingResources",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "CourseSlotId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Name",
          "dataType": "String",
          "validators": [
            {
              "name": "string"
            },
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "name": "maxLength",
              "maxLength": 50
            }
          ]
        },
        {
          "name": "ResourceFilename",
          "dataType": "String",
          "validators": [
            {
              "name": "string"
            },
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "name": "maxLength",
              "maxLength": 256
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "CourseSlot",
          "entityTypeName": "CourseSlotDto:#SM.Dto",
          "isScalar": true,
          "associationName": "CourseSlotDto_DefaultResources",
          "foreignKeyNames": [
            "CourseSlotId"
          ]
        }
      ]
    },
    {
      "shortName": "ScenarioSlotDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "CourseScenarios",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "MinutesDuration",
          "dataType": "Int32",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": -2147483648,
              "max": 2147483647,
              "name": "int32"
            },
            {
              "name": "range",
              "min": 1,
              "max": 240
            }
          ]
        },
        {
          "name": "Day",
          "dataType": "Byte",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": 0,
              "max": 255,
              "name": "byte"
            }
          ]
        },
        {
          "name": "Order",
          "dataType": "Int32",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": -2147483648,
              "max": 2147483647,
              "name": "int32"
            }
          ]
        }
      ]
    },
    {
      "shortName": "ScenarioRoleDescriptionDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "SenarioRoles",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Description",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 50,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 50,
              "name": "maxLength"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "ScenarioFacultyRoles",
          "entityTypeName": "ScenarioFacultyRoleDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ScenarioRoleDescriptionDto_ScenarioFacultyRoles",
          "invForeignKeyNames": [
            "RoleId"
          ]
        }
      ]
    },
    {
      "shortName": "ScenarioFacultyRoleDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "ScenarioFacultyRoles",
      "dataProperties": [
        {
          "name": "CourseId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "ScenarioId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "FacultyMemberId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "RoleId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "Course",
          "entityTypeName": "CourseDto:#SM.Dto",
          "isScalar": true,
          "associationName": "CourseDto_ScenarioFacultyRoles",
          "foreignKeyNames": [
            "CourseId"
          ]
        },
        {
          "name": "FacultyMember",
          "entityTypeName": "ParticipantDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ParticipantDto_ScenarioFacultyRoles",
          "foreignKeyNames": [
            "FacultyMemberId"
          ]
        },
        {
          "name": "Role",
          "entityTypeName": "ScenarioRoleDescriptionDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ScenarioRoleDescriptionDto_ScenarioFacultyRoles",
          "foreignKeyNames": [
            "RoleId"
          ]
        },
        {
          "name": "Scenario",
          "entityTypeName": "ScenarioDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ScenarioDto_ScenarioFacultyRoles",
          "foreignKeyNames": [
            "ScenarioId"
          ]
        }
      ]
    },
    {
      "shortName": "ParticipantDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "Participants",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Email",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 256,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 256,
              "name": "maxLength"
            },
            {
              "name": "emailAddress"
            }
          ]
        },
        {
          "name": "PhoneNumber",
          "dataType": "String",
          "maxLength": 32,
          "validators": [
            {
              "maxLength": 32,
              "name": "maxLength"
            },
            {
              "name": "phone"
            }
          ]
        },
        {
          "name": "AlternateEmail",
          "dataType": "String",
          "maxLength": 256,
          "validators": [
            {
              "maxLength": 256,
              "name": "maxLength"
            },
            {
              "name": "emailAddress"
            }
          ]
        },
        {
          "name": "FullName",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 256,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 256,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "DefaultDepartmentId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "DefaultProfessionalRoleId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "CourseParticipants",
          "entityTypeName": "CourseParticipantDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ParticipantDto_CourseParticipants",
          "invForeignKeyNames": [
            "ParticipantId"
          ]
        },
        {
          "name": "CourseSlotPresentations",
          "entityTypeName": "CourseSlotPresenterDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ParticipantDto_CourseSlotPresentations",
          "invForeignKeyNames": [
            "PresenterId"
          ]
        },
        {
          "name": "Department",
          "entityTypeName": "DepartmentDto:#SM.Dto",
          "isScalar": true,
          "associationName": "DepartmentDto_Participants",
          "foreignKeyNames": [
            "DefaultDepartmentId"
          ]
        },
        {
          "name": "ProfessionalRole",
          "entityTypeName": "ProfessionalRoleDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ProfessionalRoleDto_Participants",
          "foreignKeyNames": [
            "DefaultProfessionalRoleId"
          ]
        },
        {
          "name": "ScenarioFacultyRoles",
          "entityTypeName": "ScenarioFacultyRoleDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ParticipantDto_ScenarioFacultyRoles",
          "invForeignKeyNames": [
            "FacultyMemberId"
          ]
        }
      ]
    },
    {
      "shortName": "CourseSlotPresenterDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "CourseSlotPresenters",
      "dataProperties": [
        {
          "name": "CourseId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "CourseSlotId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "PresenterId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "Course",
          "entityTypeName": "CourseDto:#SM.Dto",
          "isScalar": true,
          "associationName": "CourseSlotPresenterDto_Course",
          "foreignKeyNames": [
            "CourseId"
          ]
        },
        {
          "name": "CourseSlot",
          "entityTypeName": "CourseSlotDto:#SM.Dto",
          "isScalar": true,
          "associationName": "CourseSlotPresenterDto_CourseSlot",
          "foreignKeyNames": [
            "CourseSlotId"
          ]
        },
        {
          "name": "Presenter",
          "entityTypeName": "ParticipantDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ParticipantDto_CourseSlotPresentations",
          "foreignKeyNames": [
            "PresenterId"
          ]
        }
      ]
    },
    {
      "shortName": "ProfessionalRoleDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "ProfessionalRoles",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Description",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 50,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 50,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "Category",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "string"
            }
          ],
          "enumType": "Edm.Self.ProfessionalCategory"
        }
      ],
      "navigationProperties": [
        {
          "name": "CourseParticipants",
          "entityTypeName": "CourseParticipantDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ProfessionalRoleDto_CourseParticipants",
          "invForeignKeyNames": [
            "ProfessionalRoleId"
          ]
        },
        {
          "name": "Participants",
          "entityTypeName": "ParticipantDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ProfessionalRoleDto_Participants",
          "invForeignKeyNames": [
            "DefaultProfessionalRoleId"
          ]
        }
      ]
    },
    {
      "shortName": "ScenarioDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "Scenarios",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Description",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 128,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 128,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "DepartmentId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Complexity",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "string"
            }
          ],
          "enumType": "Edm.Self.Difficulty"
        },
        {
          "name": "EmersionCategory",
          "dataType": "String",
          "validators": [
            {
              "name": "string"
            }
          ],
          "enumType": "Edm.Self.Emersion"
        },
        {
          "name": "TemplateFilename",
          "dataType": "String",
          "maxLength": 256,
          "validators": [
            {
              "maxLength": 256,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "ManequinId",
          "dataType": "Guid",
          "validators": [
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "CourseTypeId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "CourseType",
          "entityTypeName": "CourseTypeDto:#SM.Dto",
          "isScalar": true,
          "associationName": "CourseTypeDto_Scenarios",
          "foreignKeyNames": [
            "CourseTypeId"
          ]
        },
        {
          "name": "Department",
          "entityTypeName": "DepartmentDto:#SM.Dto",
          "isScalar": true,
          "associationName": "DepartmentDto_Scenarios",
          "foreignKeyNames": [
            "DepartmentId"
          ]
        },
        {
          "name": "Manequin",
          "entityTypeName": "ManequinDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ManequinDto_Scenarios",
          "foreignKeyNames": [
            "ManequinId"
          ]
        },
        {
          "name": "Resources",
          "entityTypeName": "ScenarioResourceDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ScenarioResourceDto_Scenario",
          "invForeignKeyNames": [
            "ScenarioId"
          ]
        },
        {
          "name": "ScenarioFacultyRoles",
          "entityTypeName": "ScenarioFacultyRoleDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ScenarioDto_ScenarioFacultyRoles",
          "invForeignKeyNames": [
            "ScenarioId"
          ]
        }
      ]
    },
    {
      "shortName": "ManequinDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "Manequins",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Description",
          "dataType": "String",
          "isNullable": false,
          "defaultValue": "",
          "maxLength": 50,
          "validators": [
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "maxLength": 50,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "DepartmentId",
          "dataType": "Int32",
          "validators": [
            {
              "min": -2147483648,
              "max": 2147483647,
              "name": "int32"
            }
          ]
        },
        {
          "name": "ManufacturerId",
          "dataType": "Int32",
          "isNullable": false,
          "defaultValue": 0,
          "validators": [
            {
              "name": "required"
            },
            {
              "min": -2147483648,
              "max": 2147483647,
              "name": "int32"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "Department",
          "entityTypeName": "DepartmentDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ManequinDto_Department"
        },
        {
          "name": "Manufacturer",
          "entityTypeName": "ManequinManufacturerDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ManequinDto_Manufacturer"
        },
        {
          "name": "Scenarios",
          "entityTypeName": "ScenarioDto:#SM.Dto",
          "isScalar": false,
          "associationName": "ManequinDto_Scenarios",
          "invForeignKeyNames": [
            "ManequinId"
          ]
        }
      ]
    },
    {
      "shortName": "ManequinManufacturerDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "ManequinManufacturers",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Name",
          "dataType": "String",
          "maxLength": 256,
          "validators": [
            {
              "maxLength": 256,
              "name": "maxLength"
            }
          ]
        }
      ]
    },
    {
      "shortName": "ScenarioResourceDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "ScenarioResources",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "ScenarioId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "Name",
          "dataType": "String",
          "validators": [
            {
              "name": "string"
            },
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "name": "maxLength",
              "maxLength": 50
            }
          ]
        },
        {
          "name": "ResourceFilename",
          "dataType": "String",
          "validators": [
            {
              "name": "string"
            },
            {
              "name": "required",
              "allowEmptyStrings": false
            },
            {
              "name": "maxLength",
              "maxLength": 256
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "Scenario",
          "entityTypeName": "ScenarioDto:#SM.Dto",
          "isScalar": true,
          "associationName": "ScenarioResourceDto_Scenario",
          "foreignKeyNames": [
            "ScenarioId"
          ]
        }
      ]
    },
    {
      "shortName": "RoomDto",
      "namespace": "SM.Dto",
      "autoGeneratedKeyType": "None",
      "defaultResourceName": "RoomDtoes",
      "dataProperties": [
        {
          "name": "Id",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "isPartOfKey": true,
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        },
        {
          "name": "ShortDescription",
          "dataType": "String",
          "maxLength": 32,
          "validators": [
            {
              "maxLength": 32,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "FullDescription",
          "dataType": "String",
          "maxLength": 64,
          "validators": [
            {
              "maxLength": 64,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "Directions",
          "dataType": "String",
          "maxLength": 256,
          "validators": [
            {
              "maxLength": 256,
              "name": "maxLength"
            }
          ]
        },
        {
          "name": "DepartmentId",
          "dataType": "Guid",
          "isNullable": false,
          "defaultValue": "00000000-0000-0000-0000-000000000000",
          "validators": [
            {
              "name": "required"
            },
            {
              "name": "guid"
            }
          ]
        }
      ],
      "navigationProperties": [
        {
          "name": "Courses",
          "entityTypeName": "CourseDto:#SM.Dto",
          "isScalar": false,
          "associationName": "RoomDto_Courses",
          "invForeignKeyNames": [
            "RoomId"
          ]
        },
        {
          "name": "Department",
          "entityTypeName": "DepartmentDto:#SM.Dto",
          "isScalar": true,
          "associationName": "DepartmentDto_Rooms",
          "foreignKeyNames": [
            "DepartmentId"
          ]
        }
      ]
    }
  ],
  "resourceEntityTypeMap": {
    "Countries": "CountryDto:#SM.Dto",
    "CountryLocales": "CountryLocaleCodeDto:#SM.Dto",
    "Institutions": "InstitutionDto:#SM.Dto",
    "Departments": "DepartmentDto:#SM.Dto",
    "CourseParticipants": "CourseParticipantDto:#SM.Dto",
    "Courses": "CourseDto:#SM.Dto",
    "CourseTypes": "CourseTypeDto:#SM.Dto",
    "CourseEvents": "CourseSlotDto:#SM.Dto",
    "CourseTeachingResources": "CourseTeachingResourceDto:#SM.Dto",
    "CourseScenarios": "ScenarioSlotDto:#SM.Dto",
    "SenarioRoles": "ScenarioRoleDescriptionDto:#SM.Dto",
    "ScenarioFacultyRoles": "ScenarioFacultyRoleDto:#SM.Dto",
    "Participants": "ParticipantDto:#SM.Dto",
    "CourseSlotPresenters": "CourseSlotPresenterDto:#SM.Dto",
    "ProfessionalRoles": "ProfessionalRoleDto:#SM.Dto",
    "Scenarios": "ScenarioDto:#SM.Dto",
    "Manequins": "ManequinDto:#SM.Dto",
    "ManequinManufacturers": "ManequinManufacturerDto:#SM.Dto",
    "ScenarioResources": "ScenarioResourceDto:#SM.Dto",
    "RoomDtoes": "RoomDto:#SM.Dto"
  }
})});
